preferences:
    general:
        audioLib: SoundDevice
        units: deg

window:
    size: [1920, 1080] #mac: #[3024, 1964] #
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

operating system: linux

monitor:
    name: default
    width: 69.8 # in cm, mac: 29.82 # BOLD: 
    distance: 210  # in cm, mac: 53.854 #
    gamma: 2.2 # change to 2.1 for scanning

mouse:
    visible: False

eyetracker:
    model: eyelink

mri:
    TR: 1.5  # seconds between volume acquisitions
    topup_scan: False
    topup_duration: 45 # topup scan duration in seconds (no 't's)

    #only relevant for scanning simulations
    simulate: False #set this to true to simulate a virtual scanner   
    TA: 1.5  # seconds to acquire one volume
    volumes: 225  # number of 3D volumes to obtain in a given scanning run
    sync: t  # character used as flag for simulation sync timing, default=‘5’
    skip: 0  # how many frames to silently omit initially during T1 stabilization, no sync pulse.
    sound: False  # simulate scanner noise

psychophysics:
    task: True
    bar: False
    large_range: [0.3,0.7] 
    small_range: [0.3,0.7] 

attn_task:
    stim_per_trial: 1
    signal: 6
    baseline_start: 20 #seconds
    baseline_end: 30 #seconds
    resp_keys: [1.0, 2.0] # IF USING PSYCHOPHYS BUTTON BOX: [1.0, 2.0]; AT SCANNER ['b', 'y']
    n_blanks_per_mini_block: 4
    n_mini_blocks: 5

staircase:
    n_small_trials: 9 
    n_large_low_trials: 3
    n_large_high_trials: 3
    lb: [0.1,0.9] # max easiness of task
    ub: [0.49,0.51] # max difficulty
    startPoins: [0.3,0.7]
    min: 0.01 # same as lb ub but in distance
    max: 0.9
    step_size: 0.2
    stepSizes: [0.1,0.05,0.05,0.02,0.02,0.01,0.01]
    nUp: 3
    nDown: 1

fixation stim:
  line_color: black
  line_width: 1.5
  contrast: 0.75
  default_color: 0

cue:
    duration: 0.5
    color: 1
    L_cue_length: 0.3

large_task:
    n_sections: 1
    n_rings: 30
    row_spacing: 1
    opacity: 0.8
    color1: [-0.8, 0.2, 1] 
    color2:  [1, -0.3, 0.7] 
    default_balance: 0.5
    color_range: [0.1,0.9]
    jitter: 0.15
    padding: 0 # degrees

small_task:
    n_sections: 1
    n_rings: 5
    row_spacing: 2
    opacity: 0.25
    radius: 0.1
    color1:  [-0.8, 0.2, 1] 
    color2:  [1, -0.3, 0.7] 
    default_balance: 0.5
    color_range: [0.661 , 0.339 ]

radial:
    angular_cycles: 17
    angular_res: 60
    radial_cycles: 0
    border_radius: 0.1
    n_mask_pixels: 0
    frequency: 8.0 
    outer_radius: 2
    inner_radius: 1.375

trial_types:
    low_task_opacity: 0.2
    high_task_opacity: 0.6
    absent_task_opacity: 0
    low_mapper_contrast: 0.2
    high_mapper_contrast: 0.9
    absent_mapper_contrast: 0

    '1':
        cue: 's'
        draw_large: True
        large_opacity: low
        draw_mapper: True
        mapper_contrast: low
    '2':
        cue: 's'
        draw_large: True
        large_opacity: low
        draw_mapper: True
        mapper_contrast: high
    '3':
        cue: 's'
        draw_large: True
        large_opacity: high
        draw_mapper: True
        mapper_contrast: low
    '4':
        cue: 's'
        draw_large: True
        large_opacity: high
        draw_mapper: True
        mapper_contrast: high
    '5':
        cue: 's'
        draw_large: False
        large_opacity: absent
        draw_mapper: True
        mapper_contrast: low
    '6':
        cue: 's'
        draw_large: False
        large_opacity: absent
        draw_mapper: True
        mapper_contrast: high
    '7':
        cue: 'l'
        draw_large: True
        large_opacity: low
        draw_mapper: True
        mapper_contrast: low
    '8':
        cue: 'l'
        draw_large: True
        large_opacity: low
        draw_mapper: True
        mapper_contrast: high
    '9':
        cue: 'l'
        draw_large: True
        large_opacity: high
        draw_mapper: True
        mapper_contrast: low
    '10':
        cue: 'l'
        draw_large: True
        large_opacity: high
        draw_mapper: True
        mapper_contrast: high
    '11':
        cue: 's'
        draw_large: True
        large_opacity: low
        draw_mapper: False
        mapper_contrast: absent
    '12':
        cue: 's'
        draw_large: True
        large_opacity: high
        draw_mapper: False
        mapper_contrast: absent
    '13':
        cue: 's'
        draw_large: False
        large_opacity: absent
        draw_mapper: False
        mapper_contrast: absent
    '14':
        cue: 'l'
        draw_large: True
        large_opacity: low
        draw_mapper: False
        mapper_contrast: absent
    '15':
        cue: 'l'
        draw_large: True
        large_opacity: high
        draw_mapper: False
        mapper_contrast: absent

PRF stimulus settings:
    Scanner sync: False                # set this to true to make bar move on input 't'
    Screenshot: True
    # Squares in bar: 2
    # Bar pass steps: 20                # number of steps the bar takes to traverse the aperture
    # Blanks length: 10                  # length of interbar periods (-1 in orientation). like bar pass steps, in units of TRs or bar step length
    # Bar orientations: [-1, 0,  225, -1, 90, 315, -1,  180, 45, -1,  270, 135,  -1, -1]
    # Bar width in degrees: 1.25
    # Checkers motion speed: 3          # checkers motion speed. direction is randomly up/down at each bar step
    # Size fixation dot in degrees: 0.05 # dot changes color on average every two TRs (or bar steps)
    # Bar step length: 1.5                # in seconds. this is only used if Scanner sync is set to False
    # contrast: 0.5