preferences:
    general:
        audioLib: SoundDevice
        units: deg

window:
    size: [1920, 1080] #mac: #[3024, 1964] #
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: False
    winType: pyglet
    waitBlanking: True

operating system: linux

monitor:
    name: default
    width: 69.8 # in cm, mac: 29.82 # BOLD: 
    distance: 210  # in cm, mac: 53.854 #
    gamma: 2.2 # change to 2.1 for scanning

mouse:
    visible: False

eyetracker:
    model: eyelink

mri:
    TR: 1.5  # seconds between volume acquisitions
    topup_scan: False
    topup_duration: 45 # topup scan duration in seconds (no 't's)

    #only relevant for scanning simulations
    simulate: True #set this to true to simulate a virtual scanner   
    TA: 1.5  # seconds to acquire one volume
    volumes: 214  # number of 3D volumes to obtain in a given scanning run
    sync: t  # character used as flag for simulation sync timing, default=‘5’
    skip: 0  # how many frames to silently omit initially during T1 stabilization, no sync pulse.
    sound: False  # simulate scanner noise

attn_task:
    phase_durations: [0.7,0.6,1,1.3]
    sync_trial: 5
    stim_per_trial: 1
    signal: 6
    baseline_start: 20 #seconds
    baseline_end: 30 #seconds
    resp_keys: ['1', '2'] # (B, P) IF USING PSYCHOPHYS BUTTON BOX: [1.0, 2.0]; AT SCANNER ['b', 'y']
    start_blanks: 3
    n_blanks_per_block: 4
    n_blocks: 5

staircase:
    n_small_trials: 9 
    n_large_low_trials: 3
    n_large_high_trials: 3
    lb: [0.1,0.9] # max easiness of task
    ub: [0.49,0.51] # max difficulty
    startPoints: [0.3,0.7]
    minVal: 0.01 # same as lb ub but in distance
    maxVal: 0.9
    step_size: 0.2
    stepSizes: [0.1,0.05,0.05,0.02,0.02,0.01,0.01]
    nUp: 3
    nDown: 1

fixation stim:
  line_color: black
  line_width: 1.5
  contrast: 0.75
  default_color: 0

cue:
    duration: 0.5
    color: 1
    lineLength: 0.08

large_task:
    n_sections: 1
    n_rings: 30
    row_spacing: 1
    opacity: 0.8
    color1: [-0.8, 0.2, 1] 
    color2:  [1, -0.3, 0.7] 
    default_balance: 0.5
    color_range: [0.1,0.1] #0-0.49 == pink; 0.51-1 == blue
    jitter: 0.15
    padding: 0 # degrees

small_task:
    n_sections: 1
    n_rings: 5
    row_spacing: 2
    opacity: 0.25
    radius: 0.1
    color1:  [-0.8, 0.2, 1] 
    color2:  [1, -0.3, 0.7] 
    default_balance: 0.5
    color_range: [0.9, 0.9 ] #0-0.49 == pink; 0.51-1 == blue

radial:
    angular_cycles: 7
    angular_res: 60
    radial_cycles: 0
    border_radius: 0.1
    n_mask_pixels: 0
    frequency: 8.0 
    outer_radius: 1.625
    inner_radius: 1

trial_types:
    low_task_opacity: 0.2
    high_task_opacity: 0.6
    absent_task_opacity: 0
    low_mapper_contrast: 0.075
    high_mapper_contrast: 0.9
    absent_mapper_contrast: 0

    '1':
        cue: 's'
        draw_large: True
        large_opacity: low
        draw_mapper: True
        mapper_contrast: low
        response_type: small_present
    '2':
        cue: 's'
        draw_large: True
        large_opacity: low
        draw_mapper: True
        mapper_contrast: high
        response_type: small_present
    '3':
        cue: 's'
        draw_large: True
        large_opacity: high
        draw_mapper: True
        mapper_contrast: low
        response_type: small_present
    '4':
        cue: 's'
        draw_large: True
        large_opacity: high
        draw_mapper: True
        mapper_contrast: high
        response_type: small_present
    '5':
        cue: 's'
        draw_large: False
        large_opacity: absent
        draw_mapper: True
        mapper_contrast: low
        response_type: small_absent
    '6':
        cue: 's'
        draw_large: False
        large_opacity: absent
        draw_mapper: True
        mapper_contrast: high
        response_type: small_absent
    '7':
        cue: 'l'
        draw_large: True
        large_opacity: low
        draw_mapper: True
        mapper_contrast: low
        response_type: large_low
    '8':
        cue: 'l'
        draw_large: True
        large_opacity: low
        draw_mapper: True
        mapper_contrast: high
        response_type: large_low
    '9':
        cue: 'l'
        draw_large: True
        large_opacity: high
        draw_mapper: True
        mapper_contrast: low
        response_type: large_high
    '10':
        cue: 'l'
        draw_large: True
        large_opacity: high
        draw_mapper: True
        mapper_contrast: high
        response_type: large_high
    '11':
        cue: 's'
        draw_large: True
        large_opacity: low
        draw_mapper: False
        mapper_contrast: absent
        response_type: small_present
    '12':
        cue: 's'
        draw_large: True
        large_opacity: high
        draw_mapper: False
        mapper_contrast: absent
        response_type: small_present

    '13':
        cue: 's'
        draw_large: False
        large_opacity: absent
        draw_mapper: False
        mapper_contrast: absent
        response_type: small_absent
    '14':
        cue: 'l'
        draw_large: True
        large_opacity: low
        draw_mapper: False
        mapper_contrast: absent
        response_type: large_low
    '15':
        cue: 'l'
        draw_large: True
        large_opacity: high
        draw_mapper: False
        mapper_contrast: absent
        response_type: large_high

PRF stimulus settings:
    Scanner sync: True                # set this to true to make bar move on input 't'
    Screenshot: True